server:
  port: 8082
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
    
#Eureka Server

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_mgmt?useSSL=false
    username: root
    password: root
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
             
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
      register-with-eureka: true

#method=POST, URL=http://localhost:8082/actuator/refresh      
jms:
  queue:
    queueManager: QCTA
    name: submissionConnectionFactory
    host: 124.321.123.432
    port: 1414
    channel: submissionChannel
    username: submissionuser
    password: '{cipher}ee707455b439380639a6123d79d7f728086f5bbf13a970649b4938bf9b4f76db1ffedc55a1b44ff71e1fbee7b692cf75'
    inboundQueueName: submission
    transportType: 1
    queueName: submissionQueueConfigTest2
    

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
         