server:
  port: 8082
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
    
#Eureka Server

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/account_mgmt?useSSL=false
    url: jdbc:mysql://10.0.4.22:3306/cf_ec2ff8d3_af1a_4e09_b245_f2cecfde0b17?user=5jXFlX4MpUAGeb2f&password=CBja3hRTbj1qpuHl
#    username: root
#    password: root
    username: 5jXFlX4MpUAGeb2f
    password: CBja3hRTbj1qpuHl 
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
#    base-url: http://localhost:9411/
    base-url: https://distributed-tracing-server.apps.apbg.apcf.io/
    
  rabbitmq:
#    host: localhost
    host: 10.0.4.45
#    port: 5672
#    username: guest
#    password: guest
    password: usd684tr5oq9spndrah9ghalki
    addresses: https://42e5404b-125c-4358-aa70-2aa113b71676:usd684tr5oq9spndrah9ghalki@pivotal-rabbitmq.sys.apbg.apcf.io/api/
             
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8765/eureka/
      defaultZone: https://discovery-service.apps.apbg.apcf.io/eureka/
      register-with-eureka: true

#method=POST, URL=http://localhost:8082/actuator/refresh      
jms:
  queue:
    queueManager: QCTA
    name: submissionConnectionFactory
    host: 124.321.123.432
    port: 1414
    channel: submissionChannel
    username: submissionUser    
    password: '{cipher}ee707455b439380639a6123d79d7f728086f5bbf13a970649b4938bf9b4f76db1ffedc55a1b44ff71e1fbee7b692cf75'
    inboundQueueName: submission
    transportType: 1
    queueName: submissionQueueConfigTest2
    

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
         