---      
server:
  port: 8881
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
    
#Eureka Server
spring:
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:cloud}          
  cloud:
    stream:
      bindings:
        output:
          destination: submission-topic
      kafka:
        binder:
          brokers: 52.201.157.191
          zkNodes: 52.201.157.191        
#          brokers: localhost
#          zkNodes: localhost
          defaultZkPort: 2181
          defaultBrokerPort: 9092 
      binders:
        kafka:
          default-candidate: true
  security:
    user:
      name: test
      password: test          